apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    purpose: etcd-backup
  name: etcd-backup
  namespace: etcd-backup
  labels: etcd-backup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 7200
          containers:
          - command:
            - /etcd-backup-scripts/etcd-backup.sh
            image: "etcd-backup:latest"
            imagePullPolicy: IfNotPresent
            name: etcd-backup
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /etc/ssl/etcd/
              name: certs
            - mountPath: /etc/etcd/
              name: conf
            - mountPath: /etc/kubernetes/
              name: kubeconfig
            - mountPath: /usr/local/bin
              name: scripts 
          nodeSelector:
            node-role.kubernetes.io/master: ""
          dnsPolicy: ClusterFirst
          securityContext:
            runAsUser: 0
          serviceAccount: etcd-backup-sa
          serviceAccountName: etcd-backup-sa
          hostNetwork: true
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
          volumes:
          - name: certs
            hostPath:
              path: /etc/kubernetes/static-pod-resources/etcd-member
              type: ""
          - name: conf
            hostPath:
              path: /etc/etcd
              type: ""
          - name: kubeconfig
            hostPath:
              path: /etc/kubernetes
              type: ""
          - name: scripts
            hostPath:
              path: /usr/local/bin
              type: ""
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 5
