kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1 
groupNames: null
metadata:
  name: etcd-backup-rb-privileged
  namespace: etcd-backup
  labels: etcd-backup

roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io  
  name: etcd-backup-role-privileged

subjects:
- kind: ServiceAccount
  name: etcd-backup-sa
  namespace: etcd-backup